{
 "title": "Kafka Connect Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of active connect workers",
   "type": "singlestat",
   "description": "Connect workers in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connection_count)"
    }
   ]
  },
  {
   "title": "Connector StartUp Success Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_startup_success_total"
    }
   ]
  },
  {
   "title": "Connector StartUp Failure Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_startup_failure_total"
    }
   ]
  },
  {
   "title": "Number Of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_task_count"
    }
   ]
  },
  {
   "title": "Connector Task Success Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_task_startup_success_total"
    }
   ]
  },
  {
   "title": "Connect Task StartUp Failure Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_task_startup_failure_total"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_io_ratio" }
   ]
  },
  {
   "title": "Connect Metrics: Incoming byte total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_incoming_byte_total"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network I/O Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_network_io_total" }
   ]
  },
  {
   "title": "Time Since Last Heartbeat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_coordinator_last_heartbeat_seconds_ago"
    }
   ]
  }
 ]
}