{
 "title": "Zookeeper Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Zookeeper nodes online",
   "type": "singlestat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(zookeeper_quorumsize)" }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "singlestat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections)"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_outstandingrequests", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount)"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "singlestat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"zookeeper\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"zookeeper\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"zookeeper\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_minrequestlatency", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_avgrequestlatency", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_maxrequestlatency", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Data Directory Size Per Zookeeper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_datadirsize", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}